"""initial schema

Revision ID: dbf8ddce4446
Revises: 
Create Date: 2026-08-13 10:36:23.361257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbf8ddce4446'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_usage_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('service_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('avg_latency_ms', sa.Numeric(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publisher_format_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('format_name', sa.String(length=64), nullable=False),
    sa.Column('rule_set', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('format_name')
    )
    op.create_table('reference_corpus_papers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('field_of_study', sa.String(length=255), nullable=True),
    sa.Column('embedding_vector_id', sa.Integer(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('affiliation', sa.String(length=255), nullable=True),
    sa.Column('orcid', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('researcher','reviewer','organizer','platform_admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizer_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('theme', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('tracks', sa.JSON(), nullable=True),
    sa.Column('publisher_format', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read_status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('triggered_by', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_tests', sa.Integer(), nullable=True),
    sa.Column('passed_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('failure_detail', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('server_restored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restored_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['restored_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conference_coadmins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conference_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('permission_level', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conference_reviewers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conference_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('topic_tags', sa.JSON(), nullable=True),
    sa.Column('invited_status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conference_id', 'user_id', name='uq_conference_reviewer')
    )
    op.create_table('gate_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conference_id', sa.String(length=36), nullable=False),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('threshold_soft', sa.Numeric(), nullable=True),
    sa.Column('threshold_hard', sa.Numeric(), nullable=True),
    sa.Column('is_hard_gate', sa.Boolean(), nullable=False),
    sa.CheckConstraint("NOT (rule_type = 'ai_content_pct' AND is_hard_gate = 1)", name='ck_no_hard_ai_content_gate'),
    sa.CheckConstraint("NOT (rule_type = 'plagiarism_pct' AND is_hard_gate = 1)", name='ck_no_hard_plagiarism_gate'),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('researcher_id', sa.String(length=36), nullable=False),
    sa.Column('conference_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('track', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cross_conference_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('related_submission_id', sa.String(length=36), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('match_confidence', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['related_submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviewer_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'reviewer_id', name='uq_reviewer_assignment')
    )
    op.create_table('submission_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('submission_version_id', sa.String(length=36), nullable=False),
    sa.Column('check_type', sa.String(length=32), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('pass_fail', sa.Boolean(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_version_id'], ['submission_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pdf_annotations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('submission_version_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('annotation_type', sa.String(length=16), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('position_data', sa.JSON(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('visible_to_researcher', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_version_id'], ['submission_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_assignment_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.String(length=32), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_assignment_id'], ['reviewer_assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flag_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ai_report_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('was_correct', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_report_id'], ['ai_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plagiarism_matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ai_report_id', sa.String(length=36), nullable=False),
    sa.Column('matched_paper_ext_id', sa.String(length=255), nullable=False),
    sa.Column('matched_span', sa.Text(), nullable=False),
    sa.Column('similarity_score', sa.Numeric(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['ai_report_id'], ['ai_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plagiarism_matches')
    op.drop_table('flag_feedback')
    op.drop_table('reviews')
    op.drop_table('pdf_annotations')
    op.drop_table('ai_reports')
    op.drop_table('submission_versions')
    op.drop_table('reviewer_assignments')
    op.drop_table('cross_conference_links')
    op.drop_table('submissions')
    op.drop_table('gate_rules')
    op.drop_table('conference_reviewers')
    op.drop_table('conference_coadmins')
    op.drop_table('test_runs')
    op.drop_table('notifications')
    op.drop_table('conferences')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_table('reference_corpus_papers')
    op.drop_table('publisher_format_rules')
    op.drop_table('model_usage_logs')
    # ### end Alembic commands ###
